# Generated by Django 5.2.1 on 2026-04-18 11:28

import django.db.models.deletion
import django.utils.timezone
import signatum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotarizationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kardex', models.CharField(max_length=30)),
                ('fecha_conclusion', models.CharField(blank=True, max_length=10)),
                ('folio_ini', models.CharField(blank=True, max_length=30)),
                ('folio_fin', models.CharField(blank=True, max_length=30)),
                ('papel_ini', models.CharField(blank=True, max_length=30)),
                ('papel_fin', models.CharField(blank=True, max_length=30)),
                ('num_minuta', models.CharField(blank=True, max_length=100)),
                ('num_escritura', models.CharField(blank=True, max_length=100)),
                ('fecha_escritura', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Committed'), ('CA', 'Cancelled'), ('EX', 'Expired')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                # ('expires_at', models.DateTimeField(default=signatum.models._default_reservation_expires)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatum_notarization_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Notarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kardex', models.CharField(max_length=30)),
                ('fecha_conclusion', models.CharField(blank=True, max_length=10)),
                ('folio_ini', models.CharField(blank=True, max_length=30)),
                ('folio_fin', models.CharField(blank=True, max_length=30)),
                ('papel_ini', models.CharField(blank=True, max_length=30)),
                ('papel_fin', models.CharField(blank=True, max_length=30)),
                ('num_minuta', models.CharField(blank=True, max_length=100)),
                ('num_escritura', models.CharField(blank=True, max_length=100)),
                ('fecha_escritura', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatum_notarizations_created', to=settings.AUTH_USER_MODEL)),
                ('source_reservation', models.OneToOneField(blank=True, help_text='Reservation that produced this row, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_notarization', to='signatum.notarizationreservation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
