# Generated by Django 5.2.1 on 2026-04-25 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieNotarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtipkar', models.IntegerField(default=1, help_text='Tipo de kardex this series applies to.')),
                ('nombre', models.CharField(blank=True, help_text='Optional label for the purchased range/lot.', max_length=120)),
                ('papel_ini', models.CharField(max_length=30)),
                ('papel_fin', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
