# Generated by Django 5.2.1 on 2026-05-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SisgenSoapResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kardex', models.CharField(db_index=True, max_length=32)),
                ('idkardex', models.CharField(blank=True, default='', max_length=32)),
                ('batch_index', models.PositiveSmallIntegerField(default=1)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('soap_return_status', models.CharField(blank=True, default='', max_length=64)),
                ('soap_return_message', models.TextField(blank=True, default='')),
                ('document_status', models.CharField(blank=True, default='', max_length=64)),
                ('parsed_payload', models.JSONField(default=dict)),
                ('raw_response_xml', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sisgen_soap_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sisgen_sisg_created_558427_idx'), models.Index(fields=['kardex', '-created_at'], name='sisgen_sisg_kardex_958468_idx')],
            },
        ),
    ]
