# Generated by Django 5.2.1 on 2025-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.IntegerField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(blank=True, max_length=2000, null=True)),
                ('condicion', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('incapacidad', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('num_kardex', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=3000, null=True)),
                ('num_formu', models.CharField(blank=True, max_length=30, null=True)),
                ('lugar_formu', models.CharField(blank=True, max_length=3000, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('sede_regis', models.CharField(blank=True, max_length=200, null=True)),
                ('via', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
