# Generated by Django 5.2.1 on 2025-10-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Only create DocumentosLogs - other models are unmanaged (already exist in DB)
        migrations.CreateModel(
            name='DocumentosLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kardex', models.CharField(db_index=True, help_text='Kardex reference', max_length=15)),
                ('action', models.CharField(choices=[('G', 'Generate'), ('U', 'Update'), ('O', 'Open')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentos_logs',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['kardex', '-created_at'], name='documentos__kardex_bc386e_idx'), models.Index(fields=['action', '-created_at'], name='documentos__action_42632a_idx')],
            },
        ),
    ]
